CREATE DATABASE HotelReservationDB;
USE HotelReservationDB;
CREATE TABLE ROLE (
    RoleID VARCHAR(20) PRIMARY KEY,
    RoleName VARCHAR(50) NOT NULL,
    Description VARCHAR(255)
);

CREATE TABLE ROOMTYPE (
    TypeID VARCHAR(20) PRIMARY KEY,
    TypeName VARCHAR(50) NOT NULL,
    PricePerNight DECIMAL(10, 2) NOT NULL,
    Capacity INT NOT NULL
);

CREATE TABLE GUEST (
    GuestID VARCHAR(20) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Phone VARCHAR(20),
    Email VARCHAR(100),
    ConsentAccepted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE SERVICE (
    ServiceID VARCHAR(20) PRIMARY KEY,
    ServiceName VARCHAR(100) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE STAFF (
    StaffID VARCHAR(20) PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    RoleID VARCHAR(20),
    FOREIGN KEY (RoleID) REFERENCES ROLE(RoleID)
);

CREATE TABLE ROOM (
    RoomID VARCHAR(20) PRIMARY KEY,
    Status VARCHAR(50) NOT NULL,
    TypeID VARCHAR(20),
    FOREIGN KEY (TypeID) REFERENCES ROOMTYPE(TypeID)
);

CREATE TABLE RESERVATION (
    ResID VARCHAR(20) PRIMARY KEY,
    CheckInDate DATE NOT NULL,
    CheckOutDate DATE NOT NULL,
    ResStatus VARCHAR(50) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    GuestID VARCHAR(20),
    StaffID VARCHAR(20),
    RoomID VARCHAR(20),
    FOREIGN KEY (GuestID) REFERENCES GUEST(GuestID),
    FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID),
    FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID)
);


CREATE TABLE PAYMENT (
    PaymentID VARCHAR(20) PRIMARY KEY,
    PaymentDate DATETIME NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    PaymentMethod VARCHAR(50) NOT NULL,
    PaymentStatus VARCHAR(50) NOT NULL,
    ResID VARCHAR(20),
    FOREIGN KEY (ResID) REFERENCES RESERVATION(ResID)
);

CREATE TABLE RESERVATION_HAS_SERVICE (
    ResID VARCHAR(20),
    ServiceID VARCHAR(20),
    OrderTime DATETIME NOT NULL,
    PRIMARY KEY (ResID, ServiceID),
    FOREIGN KEY (ResID) REFERENCES RESERVATION(ResID),
    FOREIGN KEY (ServiceID) REFERENCES SERVICE(ServiceID)
);