use hospital;
CREATE TABLE patientType (
    id INT
);
ALTER TABLE patientType ADD type_name VARCHAR(50);
ALTER TABLE patientType CHANGE id type_id INT;
ALTER TABLE patientType ADD PRIMARY KEY (type_id);
ALTER TABLE Patient ADD tid INT;
ALTER TABLE Patient 
ADD CONSTRAINT fk_patient_type 
FOREIGN KEY (tid) REFERENCES patientType(type_id);
CREATE TABLE Disease (
    id INT PRIMARY KEY,
    name VARCHAR(100),
    level INT
);
DROP TABLE Disease;
CREATE TABLE OnAir_Movie (
    MovieID INT UNSIGNED AUTO_INCREMENT,
    MovieName VARCHAR(255) NOT NULL,
    MovieGenre VARCHAR(100) NOT NULL,
    MovieDuration SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (MovieID)
);

CREATE TABLE Theater (
    TheaterNumber TINYINT UNSIGNED,
    Capacity SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (TheaterNumber)
);

CREATE TABLE Schedule (
    ScheduleID INT UNSIGNED AUTO_INCREMENT,
    ScheduleDateTime DATETIME NOT NULL,
    MovieID INT UNSIGNED NOT NULL,
    TheaterNumber TINYINT UNSIGNED NOT NULL,
    PRIMARY KEY (ScheduleID),
    FOREIGN KEY (MovieID) REFERENCES OnAir_Movie(MovieID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (TheaterNumber) REFERENCES Theater(TheaterNumber) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE Ticket (
    TicketID BIGINT UNSIGNED AUTO_INCREMENT,
    SeatNo VARCHAR(10) NOT NULL,
    Price DECIMAL(8,2) NOT NULL,
    ScheduleID INT UNSIGNED NOT NULL,
    PRIMARY KEY (TicketID),
    CONSTRAINT chk_unique_seat UNIQUE (ScheduleID, SeatNo),
    FOREIGN KEY (ScheduleID) REFERENCES Schedule(ScheduleID) ON DELETE RESTRICT ON UPDATE CASCADE
);
